#!/usr/bin/env bash
# Generate a minimal-tmux-status .tmuxtheme file from a tinted-shell script.
# Called by tinty as a hook for the tinted-shell item.
#
# Usage: generate-tmux-theme.sh <tinted-shell-script-path>
#
# The script extracts base16 hex colors from the tinted-shell script
# and maps them to the thm_* variables that minimal-tmux-status expects.

set -euo pipefail

SHELL_SCRIPT="$1"
THEME_FILE="$HOME/Projects/minimal-tmux-status/themes/tinted-theming.tmuxtheme"

if [ ! -f "$SHELL_SCRIPT" ]; then
  echo "generate-tmux-theme: shell script not found: $SHELL_SCRIPT" >&2
  exit 1
fi

# Extract colorXX="RR/GG/BB" lines and convert to #rrggbb
# The tinted-shell script uses slash-separated hex: color00="19/17/24"
extract_color() {
  local varname="$1"
  local hex
  hex=$(grep "^${varname}=" "$SHELL_SCRIPT" | head -1 | sed 's/.*"\(.*\)".*/\1/' | tr -d '/')
  echo "#${hex}"
}

# Base16 color slots from tinted-shell script variables:
# color00 = base00 (background)    color18 = base01
# color19 = base02                 color08 = base03
# color20 = base04                 color07 = base05 (foreground)
# color21 = base06                 color15 = base07
# color01 = base08 (red)           color16 = base09
# color03 = base0A (yellow)        color02 = base0B (green)
# color06 = base0C (cyan)          color04 = base0D (blue)
# color05 = base0E (purple)        color17 = base0F
base00=$(extract_color "color00")
base01=$(extract_color "color18")
base02=$(extract_color "color19")
base03=$(extract_color "color08")
base04=$(extract_color "color20")
base05=$(extract_color "color07")
base06=$(extract_color "color21")
base07=$(extract_color "color15")
base08=$(extract_color "color01")
base09=$(extract_color "color16")
base0A=$(extract_color "color03")
base0B=$(extract_color "color02")
base0C=$(extract_color "color06")
base0D=$(extract_color "color04")
base0E=$(extract_color "color05")
base0F=$(extract_color "color17")

# Map base16 slots to thm_* variables for minimal-tmux-status
# thm_base     = base00 (background)
# thm_surface  = base01 (elevated surface)
# thm_overlay  = base02 (overlay/popup bg, used for inactive tab bg)
# thm_muted    = base03 (muted text, prefix-off indicator)
# thm_subtle   = base04 (subtle foreground)
# thm_text     = base05 (primary text)
# thm_love     = base08 (red accent)
# thm_gold     = base09 (gold accent, prefix-on indicator)
# thm_rose     = base0A (rose/yellow accent, active tab bg)
# thm_pine     = base0B (green/teal accent)
# thm_foam     = base0C (cyan accent)
# thm_iris     = base0D (blue/purple accent)
# thm_hl_low   = base01 (same as surface — close enough)
# thm_hl_med   = base02 (pane borders)
# thm_hl_high  = base0F (high highlight)

cat > "$THEME_FILE" << EOF
# Auto-generated by tinty hook from tinted-shell scheme
# Do not edit manually — will be overwritten on theme change

thm_base="${base00}";
thm_surface="${base01}";
thm_overlay="${base02}";
thm_muted="${base03}";
thm_subtle="${base04}";
thm_text="${base05}";
thm_love="${base08}";
thm_gold="${base09}";
thm_rose="${base0A}";
thm_pine="${base0B}";
thm_foam="${base0C}";
thm_iris="${base0D}";
thm_purple="${base0E}";
thm_hl_low="${base01}";
thm_hl_med="${base02}";
thm_hl_high="${base0F}";
EOF

# Re-run minimal-tmux-status to pick up the new theme
PLUGIN_DIR="$HOME/Projects/minimal-tmux-status"
if [ -f "$PLUGIN_DIR/minimal.tmux" ] && tmux run 2>/dev/null; then
  tmux set-option -g "@minimal-tmux-theme" "tinted-theming"
  bash "$PLUGIN_DIR/minimal.tmux"
fi
