return {
  '“You should name a variable using the same care with which you name a first-born child.” — Robert C. Martin',
  '“A long descriptive name is better than a short enigmatic name. A long descriptive name is better than a long descriptive comment.”—Robert C. Martin',
  '“Any code of your own that you haven’t looked at for six or more months might as well have been written by someone else.” — Eagleson’s Law',
  '“Every time you write a comment, you should grimace and feel the failure of your ability of expression.” — Robert C. Martin',
  '“When you see commented-out code, delete it!” — Robert C. Martin',
  '“Obsolete comments are worse than no comments.” — Douglas Crockford',
  '“Comments are often lies waiting to happen. Code should speak for itself whenever possible.” — Michael Toppa',
  '“Clean code always looks like it was written by someone who cares.” — Robert C. Martin',
  '“Simplicity is prerequisite for reliability.” — Edsger W. Dijkstra',
  '“Practice, Practice, Practice! Musicians don’t only play when they are on stage in front of an audience.” — Michael Toppa',
  '“So much complexity in software comes from trying to make one thing do two things.” — Ryan Singer',
  '“The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks, and then start on the first one.” — Mark Twain',
  '“You want it in one line? Does it have to fit in 80 columns?” — Larry Wall',
  '“Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.” — John Woods',
  '“Leaving nots in a conditional like that twists my mind around at a painful angle.” — Martin Fowler',
  '“There’s nothing more permanent than a temporary hack.” — Kyle Simpson',
  '“So if you want to go fast, if you want to get done quickly, if you want your code to be easy to write, make it easy to read.” — Robert C. Martin',
  '“We like to think we spend our time power typing, but we actually spend most of our time staring into the abyss.” — Douglas Crockford',
  '“Repetition is the root of all software evil.” — Martin Fowler',
  '“Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.” — Antoine de Saint-Exupery',
  '“If I had more time, I would have written a shorter letter.” — Blaise Pascal',
  '“It can be better to copy a little code than to pull in a big library for one function. Dependency hygiene trumps code reuse.” — Rob Pyke',
  '“One of my most productive days was throwing away 1000 lines of code.” — Ken Thompson',
  '“Program testing can be used to show the presence of bugs, but never to show their absence!” — Edsger W. Dijkstra',
  '“There are only two hard things in Computer Science: cache invalidation and naming things.”— Phil Karlton',
  '“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” — Martin Fowler',
  '“Code is like humor. When you have to explain it, it’s bad.” — Cory House',
  '“I love deadlines. I like the whooshing sound they make as they fly by.” — Douglas Adams',
  '“Hey! It compiles! Ship it!” — Every programmer, ever',
  '“Weeks of coding can save you hours of planning.” — Unknown',
  '“Plans are worthless, but planning is everything.” — Dwight Eisenhower',
  '“Never trust a computer you can’t throw out a window.” — Steve Wozniak',
  '“A good programmer looks both ways before crossing a one-way street.” — Doug Linder',
  '“A full belly is little worth where the mind is starved.” - Mark Twain',
}
